# Generated by Django 4.2.23 on 2025-07-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelvendor',
            old_name='phone_number',
            new_name='vendor_name',
        ),
    ]
