# Generated by Django 4.2.23 on 2025-07-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_number_hotelvendor_vendor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelvendor',
            old_name='vendor_name',
            new_name='phone_number',
        ),
    ]
